theme: jekyll-theme-minimal
show_downloads: True
title: [Latent Heuristics]
url: Ozguc Bertug Capunaman (<a href="okc5048@psu.edu">okc5048@psu.edu</a>) 
url: Shakthi Suresh (<a href="sns5410@psu.edu">sns5410@psu.edu</a>)
description: [Ozguc Bertug Capunaman (<a href="okc5048@psu.edu">okc5048@psu.edu</a>) '\n' Shakthi Suresh (<a href="sns5410@psu.edu">sns5410@psu.edu</a>)]
...

